### ISSUE TITLE
The stage7 problem of run.sh

### ISSUE THREAD

**Issue by Wujianting** [Voice-Privacy-Challenge/Voice-Privacy-Challenge-2020#12]
Can you help me?
I am currently experiencing some problems, and I hope to get your reply. 
I encountered the problem as shown in the figure when I was running run.sh, and it couldn't proceed.
I noticed the message: the segments file is missing. But I don't know how to solve it. 
In addition, the constant prompting of env.sh problems makes me feel particularly confused.
![1](https://user-images.githubusercontent.com/33387466/129541034-916665de-e6ec-4d8f-b636-f173810e7c18.PNG)

**Comment by Natalia-T** [comment]
Hi  @Wujianting,
 
1. _"no segments file exists"_ is not a problem, it is only a warning from Kaldi. Segments files are not necessary and not used in the baseline setup.

2. You have a bug (in Kaldi) for computing mfcc features. Could you please share one of the log files listed in your screenshot (exp/make_mfcc/make_mfcc_libritts_train_other_500.*.log)?

3. Could you please share your env.sh file?

**Comment by Wujianting** [comment]
First of all thank you for your quick reply.
1.I understand the first point you listed

2.My log file is as follows:
make_mfcc_libritts_train_other_500.1.log:
[make_mfcc_libritts_train_other_500.1.log](https://github.com/Voice-Privacy-Challenge/Voice-Privacy-Challenge-2020/files/6996721/make_mfcc_libritts_train_other_500.1.log)

make_mfcc_libritts_train_other_500.2.log:
[make_mfcc_libritts_train_other_500.2.log](https://github.com/Voice-Privacy-Challenge/Voice-Privacy-Challenge-2020/files/6996722/make_mfcc_libritts_train_other_500.2.log)

make_mfcc_libritts_train_other_500.3.log:
[make_mfcc_libritts_train_other_500.3.log](https://github.com/Voice-Privacy-Challenge/Voice-Privacy-Challenge-2020/files/6996725/make_mfcc_libritts_train_other_500.3.log)

make_mfcc_libritts_train_other_500.4.log:
[make_mfcc_libritts_train_other_500.4.log](https://github.com/Voice-Privacy-Challenge/Voice-Privacy-Challenge-2020/files/6996726/make_mfcc_libritts_train_other_500.4.log)

3.The screenshot of env.sh is as follows:
![1](https://user-images.githubusercontent.com/33387466/129656865-1e6024e2-4aa6-4904-99f5-faa493246c63.PNG)

**Comment by Natalia-T** [comment]
According to env.sh and log files, your installation failed.

In particular, stage 7 fails because Kaldi has not been installed.

One possible source of this problem is the current cuda version on your computer. Which OS and which cuda version do you use?

The current setup works with the fixed Kaldi revision (in order to guarantee reproducibility of results). This Kaldi revision supports cuda-10.x and earlier versions.


If this is the case and you have a later cuda version, one solution to install everything properly is to:

1. update Kaldi up to the current version (after git clone):
- cd kaldi
- git checkout master
- git pull origin master
2. rerun install.sh


When install.sh successfully completed, in the corresponding directory the following files are created for the completed stages:
- .done-boost
- .done-flac
- .done-kaldi-src
- .done-kaldi-tools
- .done-netcdf
- .done-nii
- .done-venv

So, for the next run install.sh you should remove those files (if any) that correspond to the stages you want to rerun.



Your env.sh is incomplete (because of the reason described above).

An example of a good env.sh:

```
if [ $(which python) != /Voice-Privacy-Challenge-2020/venv/bin/python ]; then source /Voice-Privacy-Challenge-2020/venv/bin/activate; fi
export PATH=/Voice-Privacy-Challenge-2020/netcdf-c-4.3.3.1/build/bin:$PATH
export LD_LIBRARY_PATH=/Voice-Privacy-Challenge-2020/netcdf-c-4.3.3.1/build/bin:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/Voice-Privacy-Challenge-2020/boost_1_59_0/stage/lib:$LD_LIBRARY_PATH
export PATH=/Voice-Privacy-Challenge-2020/nii/CURRENNT_codes/build:$PATH
export PYTHONPATH=/Voice-Privacy-Challenge-2020/nii/CURRENNT_codes:/Voice-Privacy-Challenge-2020/nii/pyTools:/Voice-Privacy-Challenge-2020/nii_scripts:$PYTHONPATH
export nii_scripts=/Voice-Privacy-Challenge-2020/nii_scripts
export nii_dir=/Voice-Privacy-Challenge-2020/nii
```

**Comment by Wujianting** [comment]
First of all thank you very much for your quick reply.
According to your help, I have re-run 'install.sh' , and the current 'env.sh' is as shown in the figure below:
![4](https://user-images.githubusercontent.com/33387466/130183257-ef62cae2-929a-4411-bb4f-a60fd8c75dcd.PNG)
Thanks again.
However, when I run run.sh again, there are some problems in step 7.I tried to use GPU to extract xvector, I changed the use_gpu option in extract_xvectors.sh to true. As shown：
![1](https://user-images.githubusercontent.com/33387466/130183758-14e3136d-1baa-439f-a379-261d6bbb8fe5.PNG)
This does not work, my GPU does not have any programs running, and my CPU usage is still high.
![3](https://user-images.githubusercontent.com/33387466/130183898-88717dcf-092a-470a-89d1-bc62b4502ffa.PNG)
I would be grateful if you could help me.

**Comment by Wujianting** [comment]
My GPU can be used normally, thank you for your help.
